# Generated by Django 5.0 on 2024-05-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binaryconvo',
            old_name='user',
            new_name='user_id',
        ),
    ]
