# Generated by Django 5.0 on 2024-05-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_rename_user_binaryconvo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binaryconvo',
            old_name='user_id',
            new_name='user',
        ),
    ]
